export const STORIES = [
  {
    id: 1,
    date: "April 16th 2020",
    name: "The Mountains",
    by: "John Appleseed",
    imageDesktop: "/stories/desktop/mountains.jpg",
    imageMobile: "/stories/mobile/mountains.jpg",
  },
  {
    id: 2,
    date: "April 14th 2020",
    name: "Sunset Cityscapes",
    by: "by Benjamin Cruz",
    imageDesktop: "/stories/desktop/cityscapes.jpg",
    imageMobile: "/stories/mobile/cityscapes.jpg",
  },
  {
    id: 3,
    date: "April 11th 2020",
    name: "18 Days Voyages",
    by: "by Alexei Borodin",
    imageDesktop: "/stories/desktop/18-days-voyage.jpg",
    imageMobile: "/stories/mobile/18-days-voyage.jpg",
  },
  {
    id: 4,
    date: "April 9th 2020",
    name: "Architecturals",
    by: "by Samantha Brooke",
    imageDesktop: "/stories/desktop/architecturals.jpg",
    imageMobile: "/stories/mobile/architecturals.jpg",
  },
  {
    id: 5,
    date: "April 7th 2020",
    name: "World Tour 2019",
    by: "by Timothy Wagner",
    imageDesktop: "/stories/desktop/world-tour.jpg",
    imageMobile: "/stories/mobile/world-tour.jpg",
  },
  {
    id: 6,
    date: "April 3rd 2020",
    name: "Unforeseen Corners",
    by: "by William Malcolm",
    imageDesktop: "/stories/desktop/unforeseen-corners.jpg",
    imageMobile: "/stories/mobile/unforeseen-corners.jpg",
  },
  {
    id: 7,
    date: "March 29th 2020",
    name: "King on Africa: Part II",
    by: "by Tim Hillenburg",
    imageDesktop: "/stories/desktop/king-on-africa.jpg",
    imageMobile: "/stories/mobile/king-on-africa.jpg",
  },
  {
    id: 8,
    date: "March 21st 2020",
    name: "The Trip to Nowhere",
    by: "by Felicia Rourke",
    imageDesktop: "/stories/desktop/trip-to-nowhere.jpg",
    imageMobile: "/stories/mobile/trip-to-nowhere.jpg",
  },
  {
    id: 9,
    date: "March 19th 2020",
    name: "Rage of The Sea",
    by: "by Mohammed Abdule",
    imageDesktop: "/stories/desktop/rage-of-the-sea.jpg",
    imageMobile: "/stories/mobile/rage-of-the-sea.jpg",
  },
  {
    id: 10,
    date: "March 16th 2020",
    name: "Running Free",
    by: "by Michelle",
    imageDesktop: "/stories/desktop/running-free.jpg",
    imageMobile: "/stories/mobile/running-free.jpg",
  },
  {
    id: 11,
    date: "March 11th 2020",
    name: "Behind the Waves",
    by: "by Lamarr Wilson",
    imageDesktop: "/stories/desktop/behind-the-waves.jpg",
    imageMobile: "/stories/mobile/behind-the-waves.jpg",
  },
  {
    id: 12,
    date: "March 9th 2020",
    name: "Calm Waters",
    by: "by Samantha Brooke",
    imageDesktop: "/stories/desktop/calm-waters.jpg",
    imageMobile: "/stories/mobile/calm-waters.jpg",
  },
  {
    id: 13,
    date: "March 5th 2020",
    name: "The Milky Way",
    by: "by Benjamin Cruz",
    imageDesktop: "/stories/desktop/milky-way.jpg",
    imageMobile: "/stories/mobile/milky-way.jpg",
  },
  {
    id: 14,
    date: "March 4th 2020",
    name: "Night at The Dark Forest",
    by: "by  Mohammed Abdul",
    imageDesktop: "/stories/desktop/dark-forest.jpg",
    imageMobile: "/stories/mobile/dark-forest.jpg",
  },
  {
    id: 15,
    date: "March 1st 2020",
    name: "Somwarpet's Beauty",
    by: "by Michelle",
    imageDesktop: "/stories/desktop/somwarpet.jpg",
    imageMobile: "/stories/mobile/somwarpet.jpg",
  },
  {
    id: 16,
    date: "February 25th 2020",
    name: "Land of Dreams",
    by: "by William Malcolm",
    imageDesktop: "/stories/desktop/land-of-dreams.jpg",
    imageMobile: "/stories/mobile/land-of-dreams.jpg",
  },
];

export const APP_PROS = [
  {
    id: 1,
    title: "100% Responsive",
    paragraph:
      "No matter which the device you&apos;re on, our site is fully responsive and stories look beautiful on any screen.",
    icon: "/features/desktop/responsive.svg",
    width: 72,
    height: 72,
  },
  {
    id: 2,
    title: "No Photo Upload Limit",
    paragraph:
      "Our tool has no limits on uploads or bandwidth. Freely upload in bulk and share all of your stories in one go.",
    icon: "/features/desktop/no-limit.svg",
    width: 72,
    height: 36,
  },
  {
    id: 3,
    title: "Available to Embed",
    paragraph:
      "Embed Tweets, Facebook posts, Instagram media, Vimeo or YouTube videos, Google Maps, and more.",
    icon: "/features/desktop/embed.svg",
    width: 71,
    height: 72,
  },
  {
    id: 4,
    title: "Custom Domain",
    paragraph:
      "With Photosnap subscriptions you can host your stories on your own domain. You can also remove our branding!",
    icon: "/features/desktop/custom-domain.svg",
    width: 71,
    height: 72,
  },
  {
    id: 5,
    title: "Boost Your Exposure",
    paragraph:
      "Users that viewed your story or gallery can easily get notifed of new and featured stories with our built in mailing list.",
    icon: "/features/desktop/boost-exposure.svg",
    width: 71,
    height: 72,
  },
  {
    id: 6,
    title: "Drag & Drop Image",
    paragraph:
      "Easily drag and drop your image and get beautiful shots everytime. No over the top tooling to add friction to creating stories.",
    icon: "/features/desktop/drag-drop.svg",
    width: 71,
    height: 72,
  },
];
